//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinecraftAdminAssistant.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinecraftAdminAssistant.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abandoned
        ///able
        ///absolute
        ///adorable
        ///adventurous
        ///academic
        ///acceptable
        ///acclaimed
        ///accomplished
        ///accurate
        ///aching
        ///acidic
        ///acrobatic
        ///active
        ///actual
        ///adept
        ///admirable
        ///admired
        ///adored
        ///advanced
        ///afraid
        ///affectionate
        ///aged
        ///aggravating
        ///aggressive
        ///agile
        ///agitated
        ///agonizing
        ///agreeable
        ///ajar
        ///alarmed
        ///alarming
        ///alert
        ///alienated
        ///alive
        ///all
        ///amazing
        ///ample
        ///amused
        ///amusing
        ///anchored
        ///ancient
        ///angelic
        ///angry
        ///anguished
        ///animated
        ///annual
        ///another
        ///antique
        ///anxious
        ///any
        ///apprehensive
        ///appropriate
        ///apt
        ///arctic
        ///a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Adjectives {
            get {
                return ResourceManager.GetString("Adjectives", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Dice {
            get {
                object obj = ResourceManager.GetObject("Dice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alluvial fan
        ///arch
        ///archipelago
        ///ar&amp;ecirc;te
        ///arroyo
        ///atoll
        ///badlands
        ///bar
        ///barrier island
        ///basin
        ///bay
        ///bayou
        ///beach
        ///bight
        ///bluff
        ///box canyon
        ///bowl
        ///brook
        ///butte
        ///caldera
        ///canal
        ///canyon
        ///cape
        ///cataract
        ///cave
        ///cavern
        ///channel
        ///chasm
        ///chimney
        ///cinder cone
        ///cirque
        ///cliff
        ///coast
        ///coastline
        ///col
        ///continent
        ///coral reef
        ///cove
        ///crag
        ///crater lake
        ///creek
        ///crest
        ///crevasse
        ///dale
        ///dell
        ///delta
        ///depression
        ///desert
        ///divide
        ///dome
        ///drift
        ///dune
        ///equator
        ///escarpment
        ///estuary
        ///falls
        ///fault
        ///firth
        ///fissure
        ///fjord
        ///foothills
        ///fo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Landforms {
            get {
                return ResourceManager.GetString("Landforms", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap MapAdd {
            get {
                object obj = ResourceManager.GetObject("MapAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MapDelete {
            get {
                object obj = ResourceManager.GetObject("MapDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MapGo {
            get {
                object obj = ResourceManager.GetObject("MapGo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RefreshIcon {
            get {
                object obj = ResourceManager.GetObject("RefreshIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Return {
            get {
                object obj = ResourceManager.GetObject("Return", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Settings {
            get {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
